all_service_defaults:
  owner: "{{ admin.name }}"

traefik:
  name: traefik
  directory: "{{ docker_dir }}/traefik"
  domain: "home.m-kirchner.de"
  http_basic_users: "admin:$$apr1$$C7q4MwxW$$3DbS4TuKkgnkPvS8H3vZG1"  # User: admin, Password: nQ9i6yK9ORnMySE2AG26eJNSq

portainer:
  name: portainer
  admin_user: "admin"
  directory: "{{ docker_dir }}/portainer"
  admin_password: "6sjGtgBr1EkX1EARfkxovKh5p"

watchtower:
  name: watchtower
  directory: "{{ docker_dir }}/watchtower"
  http_token: "6sjGtgBr1EkX1EARfkxovKh5p"
  telegram_bot_token: ""

autoheal:
  name: autoheal
  directory: "{{ docker_dir }}/autoheal"
  telegram_bot:
    enabled: false
    token: ""
    channel_id: ""

whoami:
  name: whoami
  directory: "{{ docker_dir }}/whoami"

mariadb:
  name: mariadb
  directory: "{{ docker_dir }}/mariadb"

nextcloud:
  name: nextcloud
  directory: "{{ docker_dir }}/nextcloud"

paperless:
  name: paperless
  directory: "{{ docker_dir }}/paperless"

unifi:
  name: unifi
  directory: "{{ docker_dir }}/unifi"
