ansible_user: root
admin:
  name: root
  key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  email: "martin@m-kirchner.de"
locale: de_DE.UTF-8
timezone: Europe/Berlin
docker_dir: "/docker"
mariadb:
  backup_dir: "/srv/dev-disk-by-uuid-aae3d1d5-8831-4675-8f4d-2e9a501cc973/mariadb/backup"
nextcloud:
  domain: "nextcloud.home.m-kirchner.de"
  data_dir: "/srv/dev-disk-by-uuid-aae3d1d5-8831-4675-8f4d-2e9a501cc973/nextcloud"
  ip: 192.168.49.99
paperless:
  domain: "paperless.home.m-kirchner.de"
  directory: "{{ docker_dir }}/paperless"
  data_dir: "/srv/dev-disk-by-uuid-aae3d1d5-8831-4675-8f4d-2e9a501cc973/paperless"
  inbox_dir: "/srv/dev-disk-by-uuid-aae3d1d5-8831-4675-8f4d-2e9a501cc973/paperless-inbox"
  userId: "1028"
  groupId: "1028"
  secret: "changeme"
  db:
    user: "paperless"
unifi:
  domain: "nas.fritz.box"
  directory: "{{ docker_dir }}/unifi"
